# Generated by Django 5.1.2 on 2025-05-21 11:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntersectieSalvata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
